# Use a Node.js image with a specific version
FROM node:20

# Set working directory inside the container
WORKDIR /client

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all other frontend files
COPY . .

# Expose port 3000 for frontend
EXPOSE 3000

# Start the React app
CMD ["npm", "start"]
